rsyslog_plugin:	rsyslog_plugin.o
	g++ -Wall -g -o rsyslog_plugin rsyslog_plugin.o

rsyslog_plugin.o: rsyslog_plugin.cpp
	g++ -Wall -g -c rsyslog_plugin.cpp

clean:
	rm -f rsyslog_plugin rsyslog_plugin.o

